### ISSUE TITLE
[Feature] Change default preamble?

### ISSUE THREAD

**Issue by TheChilliPL** [mattfbacon/typst-bot#10]
It would be nice if the bot allowed changing the default preamble easily

**Comment by mattfbacon** [comment]
Do you mean per user?

**Comment by TheChilliPL** [comment]
We could have different levels of preambles: for the whole bot, per server, per user. I think it'd be very useful

**Comment by mattfbacon** [comment]
Ok, we already have a database so this is pretty feasible. I think the bot's preamble should stay static but we can definitely do guild and user-level stuff. Would the user's preamble apply for all the guilds they're in?

Also, I would probably want to limit the size of the preamble to about 1kb.

**Comment by mattfbacon** [comment]
We decided against this because the bot is mainly meant for demonstration where it is important to know the exact code. We have already had enough confusion about the existing universal preamble.
