### ISSUE TITLE
Add sample resources

### ISSUE THREAD

**Issue by frozolotl** [mattfbacon/typst-bot#14]
I think for demonstration purposes it could be useful if there were a few resources, like a bibliography and images which were included.
 
I would be willing to create a PR containing some permissively licensed resources, as well as the necessary code for inclusion, if this seems like a feature we want.

**Comment by mattfbacon** [comment]
I like that idea. I wonder, though, if it would be better to create a Typst package (something like "example" or "demo") with these files, which could then be used by bot snippets as with any other package.

**Comment by frozolotl** [comment]
Oh, that is actually a great idea. I think I will do that instead.

**Comment by mattfbacon** [comment]
Sounds good. Make sure to reference this issue in the Typst packages PR or vice versa for posterity
