### ISSUE TITLE
Quick question: how could I convert a typst string into a image ? 

### ISSUE THREAD

**Issue by slashformotion** [mattfbacon/typst-bot#2]
It seems that your bot is capable to take a typst string and output an image. I tried to extract that functionality without much success, i am still very much a rust noob.

I guess my question is, how would you do it ?

**Comment by mattfbacon** [comment]
All the rendering code is inside the worker crate. You first need to create a Sandbox and then you can call the render function passing both that sandbox and the string containing the coded
