### ISSUE TITLE
Telegram Bot Support

### ISSUE THREAD

**Issue by jassler** [mattfbacon/typst-bot#21]
This is probably out of scope for this project, but I was wondering how difficult it would be to add support for Telegram bots. Though there exists one already (https://github.com/daskol/typst-telegram-bot/) it is documented a little obscurely, I haven't managed to run it on my system. Plus, it is missing a lot of the features I love about the Discord bot, so I thought it would be easier to just adapt the Discord bot to listen to chats on Telegram instead.

**Comment by mattfbacon** [comment]
Many of the nice features of the bot depend on poise, the discord bot library we use. I think even if we managed to add telegram support the result wouldn't be much better than the other one you linked. I would focus on improving that one or adding documentation.
