### ISSUE TITLE
Docker image releases

### ISSUE THREAD

**Issue by Tokarak** [mattfbacon/typst-bot#22]
It would be convenient to have pre-built releases. Because of the complex deployment, docker images are the most reasonable. `docker-compose push` allegedly has this functionality, so maybe some maintainer can upload builds?

**Comment by mattfbacon** [comment]
I am not familiar with Docker semicolon everything darker related has been contributed by other people in the past. if you'd like to add this functionality I'd be happy to merge a PR but unfortunately I can't help with it myself.

**Comment by mattfbacon** [comment]
I think this is not worth it considering you can build an image from the github repo. And relatively complicated so I'd rather not
