### ISSUE TITLE
Bot does not Render properly

### ISSUE THREAD

**Issue by JL710** [mattfbacon/typst-bot#6]
The bot wont render anything. Even the examples just generate an empty image.
![grafik](https://github.com/mattfbacon/typst-bot/assets/76447362/9e61dcab-7e6e-4b37-86fd-3dc8ea58c587)

Trying to render math gets an error as well:
![grafik](https://github.com/mattfbacon/typst-bot/assets/76447362/7c5cdbc2-ac1b-4ba0-a28e-7731c143ad72)

I guess it could be an error with the fonts. I tried to use the ones from this repository (downloaded via git clone and zip).

**Comment by JL710** [comment]
The bug was that I did not user the git lfs. Using that fixed the issue.

**Comment by mattfbacon** [comment]
I think this is still a user experience flaw, so I improved the behavior with the above commit.
